= RoboCup Small Size League (SSL) Principles and Goals
:toc:
:toclevels: 3

NOTE: This document is currently under revision. The guiding principles were updated, but are yet to be discussed with the whole league. The long-term goals are still in the process of being revised and will be updated in the future.

== Guiding Principles

This section contains an overview of the guiding principles of the
RoboCup Small Size League (SSL). Each principle has its own section
describing the intention and its motivation. The SSL has broadly
categorized goals into two focus areas, community and technical.

Any changes in this section should be informed to and discussed with the
whole league (committees and teams).

=== Building Community

Providing goals to build community fundamentally acknowledges that
people, both inside and outside of the SSL, are the bedrock of technical
advancement and growth. Our community building principles are focused on
broadening participation within the league, enhancing the experience of
new members, and strengthening our relationships to other RoboCup
leagues.

==== Interesting Gameplay

The original idea of playing soccer with robots was to have a platform
for research that is well known to the public, so that progress in
research can more easily be seen by everyone and people will get
motivated to join us on the field. Getting and keeping attention by the
public is only possible if the games are exciting and easily
understandable. Interesting gameplay supports community and funding
engagement.

In order for the public to understand the progress of AI and robotics,
it is important to demonstrate it on interpretable tasks and systems.
Soccer is a game understood and played around the world making it an
ideal task. As we develop the rules, AI, robots and other systems in
RoboCup SSL, we keep the game understandable by the general public.

We want for any spectator to be able to understand the game at any
point, without having previous context. In other words, anyone who
arrives at any match at any point, should easily be able to determine:

* Which team is which?
* Which team is winning?
* What are the basic rules?
* What is the phase and state of the game?

==== Ease of Entry

In order to build a strong community and ensure a constant flow of fresh
ideas, new teams must have a clear path to participation and resources
to support early efforts. Additionally, the overall effort to join for
the first time and be competitive must be approachable within the
timeline of a bachelor or graduate degree program. Ease of entry is
improved by identifying problem areas, and providing community standards
either in implementation or documentation for important subsystems,
particularly systems that are important to rules compliant gameplay.

==== Educational Relevance

A key aspect of RoboCup, and the SSL, is providing a fun and relevant
educational experience to students and members of the community. The SSL
should enable participants to problem solve in an environment where
acceptable solutions are uncomplicated and optimal solutions are not
obvious or not always possible to find. Strong technical principles and
technical organization (such as software engineering) should be needed
to find success at competition. Not to be overlooked, the development of
"soft-skills" adjacent to engineering such as project management,
budgeting, and leadership is also important.

==== Scientific Discourse

One of the main objectives of the RoboCup Organization is to “promote
robotics and AI research, by offering a publicly appealing, but
formidable challenge”. The SSL supports a robust scientific discourse by
leveraging the aspects that make the SSL unique:

* Our ability to compare AI strategies with different programming
hierarchies and diverse centralized and decentralized architectures
* The league deploys AI on real, non-standardized, non-trivial,
multi-agent robot hardware
* De-emphasis on perception, localization, and human robot locomotion

By leveraging these strengths, we are more equipped to produce
researchers, students, and workers with real experience in contemporary
topics in robotics and AI. The SSL has the ability to compare approaches
that are unique to us, but also to help evaluate approaches from the MSL
and the SPL that have narrower constraints, fewer agents, or less
dynamicism. Defining our strengths and engaging with others in the
community keeps the SSL focused in a complex field. The individual SSL
teams and league as a whole should strive to publish and share their
discoveries within the SSL but also to RoboCup as a whole and the wider
AI and robotics communities.

==== Open Source

The SSL encourages all participants to open source parts or all of their
solutions, as well as to collaborate on league and broader open source
projects. Many SSL teams, including top performing Division-A teams open
source their full platform at least annually. This encourages
collaboration and progress across participants.

=== Advancing Technical Progress

The league seeks to advance technical progress across many robotics
disciplines.

==== Effective AI Progress

Effective AI progress means improving software techniques to perform
winning strategies. It also requires sound engineering so that AI can
adapt to unforeseen situations. Lastly, AI behaviour should be
explainable. Artificial Intelligence in the SSL includes classical and
machine learning approaches in isolation or working together. AI can be
applied to, but is not limited to, the sub-components control, path
planning, game state evaluation, prediction, and decision making at all
levels. The league is committed to effective AI progress for a variety
of reasons:

* There is an overwhelming student, research, and professional desire to
develop robotics AI knowledge in dynamic multi-agent environments
* Multi-agent robotics is a challenging and ongoing open
research/engineering problem that serves RoboCup and the SSL as a
complex problem space worthy of exploration and technical advancement
* Technical progress in this area makes our gameplay more interesting,
and the overall appeal of the competition higher for participants and
spectators

The SSL is a hardware-enabled multi-agent AI focused league. The SSL
maintains this emphasis through key structural elements of the game:

* The removal of localization and mapping tasks from the game through
global vision (teams aren't studying perception)
* The permission of wheeled holonomic locomotion rather than bipedal
locomotion (teams aren't studying humanoid movement)
* The relatively high agent count and high dynamicism (teams are
studying many agents adversarially interacting in a fast environment)
* Real, complex, non-standard hardware (teams can explore hardware
advantage in the context of AI)

A key aspect of the SSL commitment to effective AI progress is to fully
utilize the flexibility provided by our competition structure to explore
the realm of possible technical solutions within the previously
established areas of interest. The SSL will commit to building an
environment that supports effective AI progress by:

* Maintaining flexibility to support a wide variety of approaches to AI
architecture
** classical AI
** machine/reinforcement learning (black-box)
** centralized
** decentralized
** hybrid
** other novel solutions
* Considering and supporting contemporary trends and the desires of
industry, academia, and students

==== Quantifying Complex Results

Having a high agent count coupled with highly dynamic gameplay presents
challenges in quantifying why one team performs better than another.
This is because world assessment computational complexity grows
exponentially and the time given to assess the state and make a decision
is also reduced in a dynamic environment. The SSL strives to develop
methods to quantify decision making and performance in these
environments. Sound mathematical analysis of results assists in
communication and sharing of ideas.

==== Robustness to Real World Uncertainty

The world is messy and full of uncertainty. Between partial
observability, noise in sensors and actuation, and modeling errors it is
important that our robots and AI are robust to this messiness. The SSL
focuses on uncertainty as it relates to multi-agent behavior and sensor
fusion; perception uncertainty is strategically reduced through accurate
global vision. Robust technical approaches are more adaptable to others’
environments.

==== Striving for full autonomy

One of the big objectives of the RoboCup Organization is to be able to
have autonomous games and therefore, we want to reduce human
interference as much as possible, so as to truly be autonomous.
Therefore, we aim for a fully autonomous team of robots and fully
autonomous matches between two independent teams without any human
interaction, including no human referee.


== Long Term Goals

This section contains an overview of the long-term goals of the RoboCup Small Size League (SSL) for the next 5 to 10 years. Each goal has its own section describing the goal, its motivation in at least one guiding principle, how we will evaluate progress towards this goal and references to related work done in other RoboCup leagues and the wider robotics and AI communities. Any changes in this section should be informed to the whole league.

=== Human-in-the-loop Autonomy

==== Motivation

Our current level of technology allows us to make narrow, task-specific AI systems that perform well. However, there are still areas in SSL that are done manually right now. As a step towards general AI systems that can handle these jobs, it is important to have human supervision to make sure the systems are functioning in a way that is safe, beneficial, and aligns with user values.

==== Schedule

Created: year 2020

Expected to be implemented by 2027

==== Conforming To

Striving for full autonomy, Human Interpretability

==== Progress Measurements

Improvements can be measured in terms of time saving, efficiency or error rate.

For example,

* Existing automated procedures can be supervised by humans
* Existing manual procedures can be supported by (partial) automation

==== Achievements so far

* The SSL-Status-Board on a big screen supports the human referee and the spectators in understanding and judging the decisions of the Auto-Referee

==== References to Outside Work


==== Next Steps

[arabic]
. Introduce a physical remote control for the teams
[loweralpha]
.. For automated robot substitution
.. For changing the keeper
. Improving interaction between the human referee and the autoref (both have their strength and weaknesses; combining the strengths of both should be targeted)
. Push towards less manual exchange procedures
[loweralpha]
.. Push automated robot substitution
.. Introduce automated robot substitution after cards
. Add automated assistance for the vision expert
[loweralpha]
.. With a tool that shows quality issues and their locations

=== Reducing Stoppages

==== Motivation

We want to reduce stoppages due to hardware issues, software issues, rule violations and general game flow to a minimum. This helps in focussing on interesting parts of the game and keeping spectators attracted. More stoppages means less time for actual game time and makes it more difficult to schedule games during a tournament.

==== Schedule

Created: year 2020

Expected to be implemented by 2027

==== Conforming To

Interesting Gameplay

==== Progress Measurements

The https://ssl.robocup.org/match-statistics/[+++match statistics+++] show the relevant time usage of the different game phases.

In 2019 over all division A games, only 15% of the match time has been in RUNNING state.

==== Achievements so far

-

==== References to Outside Work

-

==== Next Steps

[arabic]
. Increase the percentage of game-on time over the competition by adapting the rules
[loweralpha]
.. Allow robot substitution while the game is running
.. Do not stop for cards (give the team 10s to automatically remove the robot)
.. Turn multiple fouls into red cards, instead of penalty kicks
.. Avoid ball placement procedure, if not necessary
.. Only stop for a limited set of fouls, increment a counter for the others

=== Automatic Adaptation of Strategy

==== Motivation

The ultimate goal of AI research is to understand and create a system of general intelligence. While this is far off in the future, we currently have the ability to make narrow-task specific AI systems. Designing these systems, combining them, and adapting them to changes in the world and new areas currently requires a large amount of human effort. We want to reduce this effort and move towards more adaptable systems, for example have better online, dynamic adaptation of strategies and learning/planning of new strategies on the fly.

==== Schedule

Created: year 2020

Expected to be implemented by 2027

==== Conforming To

Robustness to Real World Uncertainty, Interesting Gameplay

==== Progress Measurements

Can we create a team with specific weaknesses (e.g. part of the defense area is undefended consistently) and a team, having never seen this weakness, exploit it consistently?

If a team has robots with performance capabilities outside expected (e.g. much faster movement, faster direction changes, etc.) can a team adapt their models of the opponents and their strategies to account for this?

If a team develops novel hardware (e.g. Op-Amps multi-directional kicker) can teams detect on-the-fly this new capability and automatically adjust strategy and play to defend against this capability?

==== Achievements so far

-

==== References to Outside Work

-

==== Next Steps

[arabic]
. Motivate teams to work on innovations towards this goal

=== Relaxing SSL Vision constraints

==== Motivation

There is currently a global shared vision system that teams require tight tolerances on. We want to be more robust against failures in this system and less dependent on the tolerances. This may involve better filtering and processing of the data, additional local perception or shared software, but we mainly want to give teams the room for new innovations in this domain.

==== Schedule

Created: year 2020

Expected to be implemented by 2027

==== Conforming To

Robustness to Real World Uncertainty

==== Progress Measurements

The precision and reliability of the global vision system can be measured by analyzing ssl-vision messages from the network or a standard log file.

Statistics like the frame rate, the number of missing detections and the overall latency can be captured.

These statistics help in comparing the quality of ssl-vision detections in different events/matches and in identifying realistic relaxations on the tolerances.

==== Achievements so far

In 2019, the https://ssl.robocup.org/robocup-2019-technical-challenges/[+++Vision Blackout Challenge+++] has been held for the first time. It required teams to detect and intercept a ball without the global vision system.

==== References to Outside Work

-

==== Next Steps

. Build an automated tool to check these tolerances
[loweralpha]
.. A first prototype can be found https://github.com/RoboCup-SSL/ssl-quality-inspector[+++here+++]
. Define SSL-Vision tolerances that should be accepted by the teams
. Relax these tolerances over time

=== More dexterous ball manipulation

==== Motivation

One basic research topic in Robotics is to manipulate objects dexterously like humans. As we can see in a human soccer game, keeping the ball does not mean to grasp/capture the ball. However, the current style of dribbling is close to grasp/capture the ball, which enables to keep the ball with relative ease. We want to keep the ball in a new style without depending on the current dribbler. This type of skill which consists of manipulating an object without completely capturing it, is known as nonprehensile manipulation, which can be a rich topic of research in the SSL. Meanwhile, we would need to bring everyone to a similar level of ball control in the current setup before making new changes to the ball manipulation rules. Also, some considerations regarding the material of the ball could occur, in order to adjust the difficulty, i.e., changing to a ball that has a greater deceleration than the current golf ball.

==== Schedule

Created: year 2020

Expected to be implemented by 2027

==== Conforming To

Robustness to Real World Uncertainty

==== Progress Measurements

In order to achieve this goal, new types of dribbling might appear, as well as an increase in the number of passes and a decrease in the occurences of the ball leaving the field.

==== Achievements so far

-

==== References to Outside Work

* https://www.frontiersin.org/articles/10.3389/frobt.2020.00008/full[+++J. Stüber, C. Zito, and R. Stolkin: “Let’s push things forward: A survey on robot pushing,” Front. Robot. AI, 7:8, 2020, doi: 10.3389/frobt.2020.00008.+++]
* https://ieeexplore.ieee.org/document/8280543[+++F. Ruggiero, V. Lippiello, and B. Siciliano: "Nonprehensile dynamic manipulation: A survey," in IEEE Robotics and Automation Letters, vol. 3, no. 3, pp. 1711-1718, July 2018, doi: 10.1109/LRA.2018.2801939.+++]

==== Next Steps

-
