version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: |
          docker run -v $(pwd):/documents/ -u $(id -u) asciidoctor/docker-asciidoctor asciidoctor -r asciidoctor-diagram -a data-uri *.adoc
          docker run -v $(pwd):/documents/ -u $(id -u) asciidoctor/docker-asciidoctor asciidoctor-pdf -r asciidoctor-diagram *.adoc
      - store_artifacts:
          name: html
          path: sslgoals.html
      - store_artifacts:
          name: pdf
          path: sslgoals.pdf
  build_publish:
    machine:
      image: ubuntu-2204:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:W0rTlU22bwSnDW1mCY162z15NVnIH/5tIE/fDwjo4Kc"
            - "SHA256:YYeg8TEaxz4w0ZvZdE5gj/bzd5iQgtBuXeSQAeITgVI"
      - checkout
      - run: |
          docker run -v $(pwd):/documents/ -u $(id -u) asciidoctor/docker-asciidoctor asciidoctor -r asciidoctor-diagram -a data-uri *.adoc
          docker run -v $(pwd):/documents/ -u $(id -u) asciidoctor/docker-asciidoctor asciidoctor-pdf -r asciidoctor-diagram *.adoc
      - run: |
          mkdir /tmp/out
          mv ./*.html ./*.pdf /tmp/out/
          cp -r ./pages/* /tmp/out/
          git checkout gh-pages
          rm -rf * .asciidoctor
          mv /tmp/out/* .
          git config user.name "CircleCI"
          git config user.email "build-pipeline@circleci.com"
          git add .
          git commit -m "Update GitHub Pages"
          git push

workflows:
  version: 2
  docker:
    jobs:
      - build:
          filters: { branches: { ignore: master } }
      - build_publish:
          filters: { branches: { only: master } }
